import streamlit as st
import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns
import os
from sklearn.metrics import (
    accuracy_score, roc_auc_score, precision_score,
    recall_score, f1_score, matthews_corrcoef,
    confusion_matrix, classification_report,
)

st.set_page_config(
    page_title="Dry Bean Classifier",
    page_icon="",
    layout="wide",
    initial_sidebar_state="expanded",
)

st.markdown("""
<style>
    .app-title  { font-size:2.1rem; font-weight:700; color:#1b5e38; padding-bottom:0.1rem; }
    .app-sub    { color:#555; font-size:0.98rem; margin-bottom:1.4rem; }
    [data-testid="stMetricValue"]  { font-size:1.65rem !important; font-weight:700 !important; color:#1b5e38 !important; }
    [data-testid="stMetricLabel"]  { font-size:0.82rem !important; color:#666 !important; }
    .stTabs [data-baseweb="tab"]   { background:#f0f2f6; border-radius:6px 6px 0 0; padding:0.45rem 1rem; font-weight:500; }
</style>
""", unsafe_allow_html=True)

FEATURE_COLS = [
    "Area", "Perimeter", "MajorAxisLength", "MinorAxisLength",
    "AspectRation", "Eccentricity", "ConvexArea", "EquivDiameter",
    "Extent", "Solidity", "roundness", "Compactness",
    "ShapeFactor1", "ShapeFactor2", "ShapeFactor3", "ShapeFactor4",
]

MODEL_FILES = {
    "Logistic Regression":  "model/logistic_regression.pkl",
    "Decision Tree":        "model/decision_tree.pkl",
    "K-Nearest Neighbors":  "model/knn.pkl",
    "Gaussian Naive Bayes": "model/naive_bayes.pkl",
    "Random Forest":        "model/random_forest.pkl",
}

@st.cache_resource(show_spinner=False)
def load_preprocessing():
    return joblib.load("model/scaler.pkl"), joblib.load("model/label_encoder.pkl")

@st.cache_resource(show_spinner=False)
def load_model(name: str):
    return joblib.load(MODEL_FILES[name])

with st.sidebar:
    st.markdown("## Dry Bean Classifier")
    st.markdown("---")

    uploaded = st.file_uploader(
        "Upload Test Data (CSV)",
        type=["csv"],
        help="Upload the test_data.csv generated by train_models.ipynb",
    )

    model_choice = st.selectbox(
        "Classification Model",
        list(MODEL_FILES.keys()),
        index=4,
    )
    st.markdown("---")

    run_btn = st.button("▶  Run Analysis", type="primary", use_container_width=True)

    st.markdown("---")
    st.markdown("""
**Dataset**
- Source: UCI ML Repository
- Year: 2020
- Instances: 13,611
- Features: 16 morphological
- Classes: 7 bean varieties
- Task: Multi-class classification
""")

st.markdown('<p class="app-title"> Dry Bean Species Classifier</p>', unsafe_allow_html=True)
st.markdown(
    '<p class="app-sub">Multi-class classification on morphological bean features · ' +
    'UCI Dry Bean Dataset · 7 Varieties</p>',
    unsafe_allow_html=True,
)

if uploaded is None:
    col_l, col_r = st.columns([3, 2])
    with col_l:
        st.markdown("""
### How to use
1. Run `model/train_models.ipynb` to train models and generate `test_data.csv`
2. Upload **test_data.csv** using the sidebar file uploader
3. Pick a model from the dropdown
4. Click **Run Analysis**

### What you get
| Tab | Contents |
|-----|----------|
| Overview | Dataset stats · Class distribution chart |
| Model Metrics | 6 evaluation metrics · All-models comparison table |
| Confusion Matrix | Heatmap of predicted vs actual classes |
| Classification Report | Per-class precision, recall and F1 |
""")
    with col_r:
        st.info("""
**Bean classes in this dataset:**

BARBUNYA · BOMBAY · CALI  
DERMASON · HOROZ · SEKER · SIRA
""")
    st.stop()

# ── File preview while waiting for run ───────────────────────────────────────
df_raw = pd.read_csv(uploaded)

if not run_btn:
    st.success(f"Loaded **{uploaded.name}** — {df_raw.shape[0]} rows × {df_raw.shape[1]} columns")
    st.dataframe(df_raw.head(10), use_container_width=True)
    st.info("Click **▶ Run Analysis** in the sidebar to compute results.")
    st.stop()

# ── Validate ──────────────────────────────────────────────────────────────────
missing_feat = [c for c in FEATURE_COLS if c not in df_raw.columns]
if missing_feat:
    st.error(f"Missing feature columns: {missing_feat}")
    st.stop()
if "Class" not in df_raw.columns:
    st.error("The CSV must contain a **Class** column for evaluation.")
    st.stop()

# ── Predict ───────────────────────────────────────────────────────────────────
with st.spinner("Running predictions…"):
    try:
        scaler, le  = load_preprocessing()
        model       = load_model(model_choice)

        X        = df_raw[FEATURE_COLS].values
        y_true   = le.transform(df_raw["Class"].values)
        X_scaled = scaler.transform(X)
        y_pred   = model.predict(X_scaled)
        y_prob   = model.predict_proba(X_scaled)

        acc  = accuracy_score(y_true, y_pred)
        auc  = roc_auc_score(y_true, y_prob, multi_class="ovr", average="weighted")
        prec = precision_score(y_true, y_pred, average="weighted", zero_division=0)
        rec  = recall_score(y_true, y_pred, average="weighted", zero_division=0)
        f1   = f1_score(y_true, y_pred, average="weighted", zero_division=0)
        mcc  = matthews_corrcoef(y_true, y_pred)
    except Exception as exc:
        st.error(f"Prediction failed: {exc}")
        st.stop()

tab1, tab2, tab3, tab4 = st.tabs([
    " Overview",
    " Model Metrics",
    " Confusion Matrix",
    " Classification Report",
])

with tab1:
    col_a, col_b = st.columns([1, 2])
    with col_a:
        st.subheader("Test Set Info")
        st.metric("Samples",        df_raw.shape[0])
        st.metric("Features",       len(FEATURE_COLS))
        st.metric("Classes found",  df_raw["Class"].nunique())
        st.markdown(f"**Active model:** `{model_choice}`")

    with col_b:
        st.subheader("Class Distribution — Uploaded Data")
        class_counts = df_raw["Class"].value_counts().sort_values(ascending=False)
        palette = sns.color_palette("Set2", len(class_counts))
        fig, ax = plt.subplots(figsize=(7, 4))
        bars = ax.bar(class_counts.index, class_counts.values,
                      color=palette, edgecolor="white", linewidth=1.3)
        ax.set_xlabel("Bean Class", fontsize=11)
        ax.set_ylabel("Count", fontsize=11)
        ax.set_title("Test Data — Class Distribution", fontsize=13, pad=10)
        for bar, val in zip(bars, class_counts.values):
            ax.text(bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + 2, str(val),
                    ha="center", va="bottom", fontsize=9)
        plt.xticks(rotation=25, ha="right")
        plt.tight_layout()
        st.pyplot(fig, use_container_width=True)
        plt.close()

with tab2:
    st.subheader(f"Performance — {model_choice}")
    c1, c2, c3 = st.columns(3)
    c4, c5, c6 = st.columns(3)
    c1.metric("Accuracy",  f"{acc:.4f}")
    c2.metric("AUC Score", f"{auc:.4f}")
    c3.metric("Precision", f"{prec:.4f}")
    c4.metric("Recall",    f"{rec:.4f}")
    c5.metric("F1 Score",  f"{f1:.4f}")
    c6.metric("MCC",       f"{mcc:.4f}")

    st.markdown("---")
    st.subheader("All Models Comparison")

    rows = []
    for mname in MODEL_FILES:
        if os.path.exists(MODEL_FILES[mname]):
            m    = load_model(mname)
            yp   = m.predict(X_scaled)
            yprb = m.predict_proba(X_scaled)
            rows.append({
                "Model":     mname,
                "Accuracy":  round(accuracy_score(y_true, yp), 4),
                "AUC":       round(roc_auc_score(y_true, yprb, multi_class="ovr", average="weighted"), 4),
                "Precision": round(precision_score(y_true, yp, average="weighted", zero_division=0), 4),
                "Recall":    round(recall_score(y_true, yp, average="weighted", zero_division=0), 4),
                "F1 Score":  round(f1_score(y_true, yp, average="weighted", zero_division=0), 4),
                "MCC":       round(matthews_corrcoef(y_true, yp), 4),
            })

    if rows:
        comp = pd.DataFrame(rows).set_index("Model")
        styled = comp.style.highlight_max(
            axis=0, props="background-color:#c6efce;color:#276228;font-weight:bold"
        ).format("{:.4f}")
        st.dataframe(styled, use_container_width=True)
        winner = comp["F1 Score"].idxmax()
        st.caption(f"Green cells = best value per metric.  Best overall (F1 Score): **{winner}**")

with tab3:
    st.subheader(f"Confusion Matrix — {model_choice}")
    cm  = confusion_matrix(y_true, y_pred)
    fig, ax = plt.subplots(figsize=(9, 7))
    sns.heatmap(
        cm, annot=True, fmt="d", cmap="YlGn",
        xticklabels=le.classes_, yticklabels=le.classes_,
        linewidths=0.5, linecolor="white", ax=ax,
    )
    ax.set_xlabel("Predicted Label", fontsize=12, labelpad=10)
    ax.set_ylabel("True Label",      fontsize=12, labelpad=10)
    ax.set_title(f"Confusion Matrix — {model_choice}", fontsize=13, pad=15)
    plt.xticks(rotation=30, ha="right", fontsize=10)
    plt.yticks(rotation=0,  fontsize=10)
    plt.tight_layout()
    st.pyplot(fig, use_container_width=True)
    plt.close()
    st.caption("Diagonal = correct predictions.  Off-diagonal = misclassifications.")

with tab4:
    st.subheader(f"Classification Report — {model_choice}")
    report = classification_report(
        y_true, y_pred, target_names=le.classes_, output_dict=True, zero_division=0
    )
    report_df = pd.DataFrame(report).T.round(4)
    st.dataframe(report_df, use_container_width=True)
    st.markdown("---")
    st.markdown(
        f"**Model:** `{model_choice}` &nbsp;|&nbsp; "
        f"**Samples:** `{len(df_raw)}` &nbsp;|&nbsp; "
        "**Classes:** " + ", ".join(f"`{c}`" for c in le.classes_)
    )
